### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by cabudies** [saleor/saleor-sdk#125]
How to work on local development for the sdk and map it with saleor-storefront?

**Comment by jatinbharadwaj** [comment]
clone saleor-sdk switch into a stable branch like master
Run these commands
```
$ npm i 
$ cd lib 
$ npm link
```
now, clone saleor-storefront
```
$ cd <your storefront path>
```
Remove, cut that saleor-sdk from package.json
```
$ npm i
$ npm link @saleor/sdk
Paste saleor-sdk that been cut previously in package.json
```

these are the steps I followed and it worked.
Hope it'll work for you as well✌🏼

**Comment by ace-han** [comment]
> clone saleor-sdk switch into a stable branch like master Run these commands
> 
> ```
> $ npm i 
> $ cd lib 
> $ npm link
> ```
> 
> now, clone saleor-storefront
> 
> ```
> $ cd <your storefront path>
> ```
> 
> Remove, cut that saleor-sdk from package.json
> 
> ```
> $ npm i
> $ npm link @saleor/sdk
> Paste saleor-sdk that been cut previously in package.json
> ```
> 
> these are the steps I followed and it worked. Hope it'll work for you as well✌🏼

@jatinbharadwaj I tried as what you said. However, I could not find the `lib` folder, will you kindly help?
```shell
$ npm i 
$ cd lib  # <-- where is this folder?
$ npm link
```

![image](https://user-images.githubusercontent.com/1177332/137591228-31903e49-e949-44cc-9484-e7aa8bdad855.png)

**Comment by kudryashov13** [comment]
> > clone saleor-sdk switch into a stable branch like master Run these commands
> > ```
> > $ npm i 
> > $ cd lib 
> > $ npm link
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > now, clone saleor-storefront
> > ```
> > $ cd <your storefront path>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Remove, cut that saleor-sdk from package.json
> > ```
> > $ npm i
> > $ npm link @saleor/sdk
> > Paste saleor-sdk that been cut previously in package.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > these are the steps I followed and it worked. Hope it'll work for you as well✌🏼
> 
> @jatinbharadwaj I tried as what you said. However, I could not find the `lib` folder, will you kindly help?
> 
> ```shell
> $ npm i 
> $ cd lib  # <-- where is this folder?
> $ npm link
> ```
> 
> ![image](https://user-images.githubusercontent.com/1177332/137591228-31903e49-e949-44cc-9484-e7aa8bdad855.png)

Do
```
npm run prepare
```
it will create /lib directory
