### ISSUE TITLE
How to add additional fields to product list query without editing or monkey-patching saleor-sdk library?

### ISSUE THREAD

**Issue by gleniat** [saleor/saleor-sdk#143]
Hello,

I'd like to fetch more fields from API. For example, I'd like to add the `description` field to the list of products.

in `src/pages/product/[slug].ts` in `saleor-storefont`, product list is retrieved by `api.products.getList()`

```js
export const getStaticPaths: GetStaticPaths<
  ProductPageProps["params"]
> = async () => {
  const { api } = await getSaleorApi();
  const { data } = await exhaustList(
    api.products.getList({
      first: staticPathsFetchBatch,
      channel: channelSlug,
    })
  );
  ...
};
```

I'm getting data like this:

```
{
id: "UHJvZHVjdDo3NjQ0",
name: "Test product",
slug: "test-product",
seoDescription: "Test product SEO description",
isAvailableForPurchase: true,
availableForPurchase: "2021-10-10",
seoTitle: "Test Product SEO title",
thumbnail: {
      url: "https://www.example.com/__sized__/products/0123456-thumbnail-255x255-70.jpg",
      alt: "",
    }
thumbnail2x: {
      url: "https://www.example.com/__sized__/products/0123456-thumbnail-510x510-70.jpg",
    }
}
```

I'm missing `description` field there.

I have found that the original query which is sent to the backend comes from `lib/fragments/products.js`:

```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.productFragment = exports.productPricingFragment = exports.productVariantFragment = exports.selectedAttributeFragment = exports.baseProductFragment = void 0;
const graphql_tag_1 = __importDefault(require("graphql-tag"));
const checkout_1 = require("./checkout");
exports.baseProductFragment = graphql_tag_1.default `
  fragment BaseProduct on Product {
    id
    name
    slug
    seoDescription
    isAvailableForPurchase
    availableForPurchase
    seoTitle
    thumbnail {
      url
      alt
    }
    thumbnail2x: thumbnail(size: 510) {
      url
    }
  }
`;
```

When I add the `description` field to `exports.baseProductFragment`, I get description data in the storefront, which is good.

However, editing external library files is not the correct way how to handle this. **I'd like to know how to override the default product query from the storefront code to get the data I need,** without editing or monkey-patching the `saleor-sdk` external library files. Is there any better way to solve this issue?

Thank you

**Comment by jwm0** [comment]
There's no other built-in way to override the response types, while it's fairly easy to add the ability to extend the query it's less trivial to make it fully typed. For the latest SDK we completely stripped out all the public mutations and instead focused on an easy plug'n'play authentication with session persistance. While it's possible to create an SDK that mimics our API 1:1, this means having to maintain a whole separate documentation and always playing catch-up. Instead, our focus is on improving core API documentation, tutorial section and encouraging people to write their own queries/mutations to take full advantage of GraphQL and its ecosystem.
