### ISSUE TITLE
Password recovery using saleor-sdk

### ISSUE THREAD

**Issue by Mak-Ta-Reque** [saleor/saleor-sdk#162]
Hi, I am trining to reset the password in the saleor-storefront using saleor-sdk. Is the sdk can handle resetting the user password.
Which function shall I import from sdk.

**Comment by timuric** [comment]
@Mak-Ta-Reque you can use `RequestPasswordReset` mutation. The goal SDK is to provide only handful of commonly used actions, for the most part please use GraphQL API
