### ISSUE TITLE
Future of saleor-sdk

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-sdk#171]
Since Saleor is GraphQL-first API, there is no need to build a classic "SDK" that hides common operations - this is handy for REST APIs.

We aim to provide good docs and using tools around graphQL (like graphql codegen), that automatically "generates SDK" exactly for client needs.

It seems that only benefit of `saleor-sdk` is to provide reusable logic of authentication. 

This issue is to track decision process - of following possibilities:

1. Deprecate this package and make auth logic part of client (Dashboard, Storefront)
2. Inject this package into Dashboard/Storefront 
3. Extract new package, specific to auth (eg saleor/auth-sdk or saleor/auth), reuse it in Dashboard, Storefront + custom storefronts

**Comment by mmiszy** [comment]
Saleor SDK is DEPRECATED. See the announcement: https://github.com/saleor/saleor/discussions/12891
