### ISSUE TITLE
Saleor SDK is not compatible with React 18

### ISSUE THREAD

**Issue by jonybekov** [saleor/saleor-sdk#174]
I am facing a TS error when passing children to Saleor Provider: 
``Property 'children' does not exist on type 'IntrinsicAttributes & { client: SaleorClient; }'.``
![image](https://user-images.githubusercontent.com/39439363/197999519-75256a35-ecb6-4c57-b17e-1116675bc338.png)
The reason is React 18 removed children prop from React.FC.
Please make it compatible with React 18.

**Comment by mmiszy** [comment]
https://github.com/saleor/saleor-sdk/releases/tag/v0.7.0
