### ISSUE TITLE
Question: Usage for React Native

### ISSUE THREAD

**Issue by sebasalvarado** [saleor/saleor-sdk#42]
Hi Saleor Team, thanks for abstracting the `sdk` logic into this package, it will be great going forward.

I'm trying to build a React Native mobile app to use with our Saleor back-end, right now we can't use the SDK because it makes use of some Browser APIs, is there any plan to make this runtime agnostic? So that we can use the library just in javascript not only on the browser?

Thanks!

**Comment by orzechdev** [comment]
Hi @sebasalvarado 

Yes, there are such plans, and actually, we are working on it right now. As soon as support for it is available, we will release a new version.

**Comment by sebasalvarado** [comment]
Thanks for your answer! Looking forward when support is available for this!

**Comment by cristian05** [comment]
Any updates?

**Comment by pgiki** [comment]
I am wondering if there are any updates regarding this issue?

**Comment by cristian05** [comment]
anyone interested in collaborating to make saleor skd compatible with react native? @pgiki @sebasalvarado

**Comment by cabudies** [comment]
@sebasalvarado, @crisfcodes, @pgiki, @orzechdev  can you guide me on how to separate the saleor/sdk. I need to make changes to a few of the apis.
