### ISSUE TITLE
CheckoutComplete doesn't return Data for 3d secure payment

### ISSUE THREAD

**Issue by DidoMarchet** [saleor/saleor-sdk#66]
Hi,
I'm trying to figure out 3d secure payment with Stripe.
I need to retrieve the confirmationData from the gateway.
When I submit **completeCheckout** returns this array
`[{"data": {"checkoutComplete": {"errors": [], "order": null, "confirmationNeeded": true, "confirmationData": "{}", "__typename": "CheckoutComplete"}}}]` but **confirmationData** is empty. 

The storefront demo has the same issue.

Do you know how to figure out this problem because it's crucial for payment.

Thanks in advance and kind regards,

Davide

**Comment by ibanezzaro** [comment]
Hey @DidoMarchet, 
you're better off implementing it through saleor backend. You should watch for the field "requires_action" in stripe CreateIntent API, then pass that data to saleor-storefront, it'll let you render an iframe

**Comment by maarcingebala** [comment]
3D Secure for Stripe isn't currently supported in Saleor, this will be fixed in the incoming Saleor 3.0 version.

**Comment by ibanezzaro** [comment]
@maarcingebala I actually managed to implement it and it's working pretty well at the moment, I was planning on opening a PR

**Comment by maarcingebala** [comment]
Sure, feel free to open a PR! Did you also implement related changes in SDK or in Saleor Storefront? One part that needs to be changed is the backend - to return data for 3DS redirect, but the redirect needs to be handled in the storefront as well.

**Comment by iba-1** [comment]
> Sure, feel free to open a PR! Did you also implement related changes in SDK or in Saleor Storefront? One part that needs to be changed is the backend - to return data for 3DS redirect, but the redirect needs to be handled in the storefront as well.

I've implemented some related changes in Storefront, but I'm not using any page to redirect from, I'm opening the 3DS confirmation in an iframe embedded in the checkoutReview page. I prefer it this way as I'm not redirecting the user, in a crucial moment, out of our website. This is the main reason why I haven't opened a PR yet, as I think it won't be accepted this way. 

Sorry for hijacking this issue :(
