### ISSUE TITLE
Adapting saleor-sdk to react-native

### ISSUE THREAD

**Issue by crisfcodes** [saleor/saleor-sdk#82]
saleor-sdk source code has two main Api's: `APIProxy` and `SaleorAPI`. `APIProxy` exist as independent API and belongs to `SaleorAPI` too as `field`, in `SaleorAPI`, the following comment is provided:

```typescript
/**
   * @deprecated Please do not use it anymore. Reference to API Proxy will be removed in future.
   * Now it just exists for legacy React hooks, which also will be removed.
   */
  legacyAPIProxy: APIProxy;
```

According to the above, and considering that I am trying to adapt saleor-sdk to react native, can I remove this `APIProxy` from source code? I would like to hear the opinion from a member of the saleor-sdk team.

### NOTES

things I am working on:

1. Adapting the browser `LocalStore` to the native store as `AsyncStorage`.
2. Upgrading Apollo client from version 2 to version 3.
3. Trying to improve some code, this includes removing code that is legacy or not necessary.

**Comment by gax97** [comment]
I suggest that you consider making the sdk with https://github.com/mrousavy/react-native-mmkv instead of AsyncStorage. It is a better/faster alternative to AsyncStorage and you also get API that is synchronous just like local storage.

**Comment by cristian05** [comment]
@gax97 this library its supported by expo? I'm implementing some test with this library in expo app and thrown a lot of erros.

**Comment by gax97** [comment]
I didn't use it with expo, but it seems like your are right 😏
